import {
  PayrollAdjustmentSource,
  PayrollAdjustmentType,
} from "@prisma/client"
import { NextRequest, NextResponse } from "next/server"
import { getServerSession } from "next-auth"
import { z } from "zod"
import { authOptions } from "@/lib/auth"
import { notifyPayrollAdjustmentAdded } from "@/lib/notification-service"
import { synchronizePayrollRecordWithAdjustments } from "@/lib/payroll/payroll-adjustments"
import { prisma } from "@/lib/prisma"

export const dynamic = "force-dynamic"

const payrollAdjustmentSchema = z.object({
  type: z.nativeEnum(PayrollAdjustmentType),
  source: z.nativeEnum(PayrollAdjustmentSource),
  reason: z.string().trim().min(1, "Reason is required").max(500),
  amount: z.coerce.number().positive("Amount must be greater than zero"),
})

export async function POST(
  req: NextRequest,
  { params }: { params: { recordId: string } }
) {
  try {
    const session = await getServerSession(authOptions)

    if (!session?.user || session.user.role !== "admin") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const body = await req.json()
    const validated = payrollAdjustmentSchema.safeParse(body)

    if (!validated.success) {
      return NextResponse.json(
        { error: "Invalid input", details: validated.error.errors },
        { status: 400 }
      )
    }

    const record = await prisma.payrollRecord.findFirst({
      where: {
        id: params.recordId,
        academyId: session.user.academyId,
      },
      select: {
        id: true,
      },
    })

    if (!record) {
      return NextResponse.json(
        { error: "Payroll record not found" },
        { status: 404 }
      )
    }

    const adjustment = await prisma.$transaction(async (tx) => {
      const created = await tx.payrollAdjustment.create({
        data: {
          payrollRecordId: record.id,
          type: validated.data.type,
          source: validated.data.source,
          reason: validated.data.reason.trim(),
          amount: validated.data.amount,
          isAutoGenerated: false,
          createdByUserId: session.user.id,
        },
        select: {
          id: true,
          type: true,
          source: true,
          reason: true,
          amount: true,
        },
      })

      await tx.payrollRecord.update({
        where: { id: record.id },
        data: {
          salarySlipUrl: null,
          updatedByUserId: session.user.id,
        },
      })

      return created
    })

    await synchronizePayrollRecordWithAdjustments({
      recordId: record.id,
      actorUserId: session.user.id,
    })

    await notifyPayrollAdjustmentAdded(adjustment.id)

    return NextResponse.json({
      adjustment: {
        ...adjustment,
        amount: Number(adjustment.amount),
      },
    })
  } catch (error) {
    console.error("Failed to create payroll adjustment:", error)
    return NextResponse.json(
      { error: "Failed to create payroll adjustment" },
      { status: 500 }
    )
  }
}
