import { PayrollAdjustmentType } from "@prisma/client"
import { prisma } from "@/lib/prisma"
import { renderPdfFromHtml } from "@/lib/pdf/browser"
import {
  AcademyBranding,
  buildPDFFilename,
  escapeHtml,
  formatCurrencyForPDF,
  formatDateForPDF,
  resolvePdfImageSource,
  renderAcademyHeader,
  renderPDFFooter,
  renderTextBlock,
} from "@/lib/pdf/pdf-utils"
import {
  calculatePayrollBreakdownTotals,
  payrollAdjustmentTypeLabels,
  payrollRoleLabels,
} from "@/lib/payroll/payroll-utils"

export interface PayrollSlipPDFData {
  record: {
    id: string
    payYear: number
    payMonth: number
    role: "admin" | "teacher"
    grossAmount: number
    paidAmount: number
    currency: string
    status: string
    paymentDate: Date | null
    notes: string | null
    isFinalized: boolean
    finalizedAt: Date | null
    user: {
      firstName: string
      lastName: string
      email: string
      employeeId: string | null
    }
    adjustments: Array<{
      id: string
      type: PayrollAdjustmentType
      reason: string
      amount: number
      isAutoGenerated: boolean
    }>
  }
  academy: AcademyBranding
}

function formatPayrollPeriodLabel(payYear: number, payMonth: number) {
  return new Intl.DateTimeFormat("en-US", {
    month: "long",
    year: "numeric",
  }).format(new Date(Date.UTC(payYear, payMonth - 1, 1)))
}

export async function fetchPayrollSlipData(
  recordId: string
): Promise<PayrollSlipPDFData | null> {
  const record = await prisma.payrollRecord.findUnique({
    where: { id: recordId },
    select: {
      id: true,
      payYear: true,
      payMonth: true,
      role: true,
      grossAmount: true,
      paidAmount: true,
      currency: true,
      status: true,
      paymentDate: true,
      notes: true,
      isFinalized: true,
      finalizedAt: true,
      user: {
        select: {
          firstName: true,
          lastName: true,
          email: true,
          teacherProfile: {
            select: {
              employeeId: true,
            },
          },
        },
      },
      adjustments: {
        orderBy: [
          {
            type: "asc",
          },
          {
            createdAt: "asc",
          },
        ],
        select: {
          id: true,
          type: true,
          reason: true,
          amount: true,
          isAutoGenerated: true,
        },
      },
      academy: {
        select: {
          name: true,
          logoUrl: true,
          primaryColor: true,
          secondaryColor: true,
          contactEmail: true,
        },
      },
    },
  })

  if (!record) {
    return null
  }

  const academyLogoUrl = await resolvePdfImageSource(record.academy.logoUrl)

  return {
    record: {
      id: record.id,
      payYear: record.payYear,
      payMonth: record.payMonth,
      role: record.role as "admin" | "teacher",
      grossAmount: Number(record.grossAmount),
      paidAmount: Number(record.paidAmount),
      currency: record.currency,
      status: record.status,
      paymentDate: record.paymentDate,
      notes: record.notes,
      isFinalized: record.isFinalized,
      finalizedAt: record.finalizedAt,
      user: {
        firstName: record.user.firstName,
        lastName: record.user.lastName,
        email: record.user.email,
        employeeId: record.user.teacherProfile?.employeeId || null,
      },
      adjustments: record.adjustments.map((adjustment) => ({
        id: adjustment.id,
        type: adjustment.type,
        reason: adjustment.reason,
        amount: Number(adjustment.amount),
        isAutoGenerated: adjustment.isAutoGenerated,
      })),
    },
    academy: {
      name: record.academy.name,
      logoUrl: academyLogoUrl,
      primaryColor: record.academy.primaryColor,
      secondaryColor: record.academy.secondaryColor,
      contactEmail: record.academy.contactEmail,
    },
  }
}

function renderPayrollSlipHTML(data: PayrollSlipPDFData) {
  const { academy, record } = data
  const breakdown = calculatePayrollBreakdownTotals(
    record.grossAmount,
    record.adjustments.map((adjustment) => ({
      type: adjustment.type,
      amount: adjustment.amount,
    }))
  )

  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8" />
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
            color: #111827;
            margin: 0;
            padding: 24px;
            line-height: 1.5;
          }
          .container {
            max-width: 840px;
            margin: 0 auto;
          }
          .summary-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 12px 20px;
            background: #f9fafb;
            border-radius: 12px;
            padding: 18px;
            margin-bottom: 24px;
          }
          .label {
            color: #6b7280;
            font-weight: 600;
            margin-right: 6px;
          }
          .card {
            border: 1px solid #e5e7eb;
            border-radius: 12px;
            padding: 18px;
            margin-bottom: 18px;
            page-break-inside: avoid;
          }
          .section-title {
            color: ${academy.primaryColor};
            font-size: 18px;
            font-weight: 700;
            margin-bottom: 12px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 12px;
          }
          th, td {
            border-bottom: 1px solid #e5e7eb;
            padding: 10px 0;
            text-align: left;
            vertical-align: top;
          }
          th {
            color: #6b7280;
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: 0.04em;
          }
          .amount {
            text-align: right;
          }
        </style>
      </head>
      <body>
        <div class="container">
          ${renderAcademyHeader(academy)}

          <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 24px;">
            <div>
              <h2 style="margin: 0 0 6px;">Salary Slip</h2>
              <p style="margin: 0; color: #6b7280;">
                ${escapeHtml(formatPayrollPeriodLabel(record.payYear, record.payMonth))}
              </p>
            </div>
            <div style="text-align: right;">
              <div style="font-size: 28px; font-weight: 700; color: ${academy.primaryColor};">
                ${formatCurrencyForPDF(breakdown.netPayable, record.currency)}
              </div>
              <div style="color: #6b7280;">Net Payable</div>
            </div>
          </div>

          <div class="summary-grid">
            <div>
              <span class="label">Employee:</span>
              ${escapeHtml(record.user.firstName)} ${escapeHtml(record.user.lastName)}
            </div>
            <div>
              <span class="label">Role:</span>
              ${escapeHtml(payrollRoleLabels[record.role])}
            </div>
            <div>
              <span class="label">Employee ID:</span>
              ${escapeHtml(record.user.employeeId || "Not assigned")}
            </div>
            <div>
              <span class="label">Status:</span>
              ${escapeHtml(record.status)}
            </div>
            <div>
              <span class="label">Payment Date:</span>
              ${record.paymentDate ? formatDateForPDF(record.paymentDate) : "Not recorded"}
            </div>
            <div>
              <span class="label">Finalized:</span>
              ${record.isFinalized ? formatDateForPDF(record.finalizedAt || new Date()) : "Draft"}
            </div>
          </div>

          <div class="card">
            <div class="section-title">Salary Breakdown</div>
            <table>
              <tbody>
                <tr>
                  <td>Basic Salary</td>
                  <td class="amount">${formatCurrencyForPDF(breakdown.baseSalary, record.currency)}</td>
                </tr>
                <tr>
                  <td>Total Bonuses</td>
                  <td class="amount">${formatCurrencyForPDF(breakdown.totalBonuses, record.currency)}</td>
                </tr>
                <tr>
                  <td>Total Deductions</td>
                  <td class="amount">${formatCurrencyForPDF(-breakdown.totalDeductions, record.currency)}</td>
                </tr>
                <tr>
                  <td>Advance Adjustments</td>
                  <td class="amount">${formatCurrencyForPDF(-breakdown.totalAdvanceAdjustments, record.currency)}</td>
                </tr>
                <tr>
                  <td><strong>Net Payable</strong></td>
                  <td class="amount"><strong>${formatCurrencyForPDF(breakdown.netPayable, record.currency)}</strong></td>
                </tr>
                <tr>
                  <td>Paid Amount</td>
                  <td class="amount">${formatCurrencyForPDF(record.paidAmount, record.currency)}</td>
                </tr>
              </tbody>
            </table>
          </div>

          <div class="card">
            <div class="section-title">Adjustments</div>
            ${
              record.adjustments.length > 0
                ? `
              <table>
                <thead>
                  <tr>
                    <th>Type</th>
                    <th>Reason</th>
                    <th>Source</th>
                    <th class="amount">Amount</th>
                  </tr>
                </thead>
                <tbody>
                  ${record.adjustments
                    .map(
                      (adjustment) => `
                    <tr>
                      <td>${escapeHtml(payrollAdjustmentTypeLabels[adjustment.type])}</td>
                      <td>${escapeHtml(adjustment.reason)}</td>
                      <td>${adjustment.isAutoGenerated ? "Automatic" : "Manual"}</td>
                      <td class="amount">${
                        adjustment.type === PayrollAdjustmentType.bonus
                          ? formatCurrencyForPDF(adjustment.amount, record.currency)
                          : formatCurrencyForPDF(-adjustment.amount, record.currency)
                      }</td>
                    </tr>
                  `
                    )
                    .join("")}
                </tbody>
              </table>
            `
                : `
              <p style="margin: 0; color: #6b7280;">No bonuses or deductions were applied to this payroll record.</p>
            `
            }
          </div>

          ${
            record.notes
              ? `
            <div class="card">
              <div class="section-title">Notes</div>
              <p style="margin: 0;">${renderTextBlock(record.notes)}</p>
            </div>
          `
              : ""
          }

          ${renderPDFFooter(academy)}
        </div>
      </body>
    </html>
  `
}

export async function generatePayrollSlipPDFBuffer(data: PayrollSlipPDFData) {
  return renderPdfFromHtml(renderPayrollSlipHTML(data))
}

export async function generatePayrollSlipPDF(recordId: string) {
  const data = await fetchPayrollSlipData(recordId)

  if (!data) {
    return null
  }

  return generatePayrollSlipPDFBuffer(data)
}

export function getPayrollSlipPDFFilename(record: PayrollSlipPDFData["record"]) {
  const employeeName = `${record.user.firstName}_${record.user.lastName}`.replace(
    /\s+/g,
    "_"
  )

  return buildPDFFilename(
    `salary_slip_${employeeName}_${record.payYear}_${String(record.payMonth).padStart(2, "0")}`,
    record.id
  )
}
