import {
  PayrollAdjustmentSource,
  PayrollAdjustmentType,
  PayrollRuleMode,
  PayrollStatus,
  Role,
  SessionStatus,
} from "@prisma/client"
import { prisma } from "@/lib/prisma"
import {
  calculatePayrollRuleAmount,
  calculatePayrollBreakdownTotals,
  getPayrollPeriodBounds,
  roundPayrollAmount,
  toNumber,
} from "@/lib/payroll/payroll-utils"

export interface AcademyPayrollSettingsData {
  id: string
  academyId: string
  autoApplyLateDeductions: boolean
  lateGraceMinutes: number
  lateDeductionMode: PayrollRuleMode
  lateDeductionValue: number
  autoApplyAbsenceDeductions: boolean
  absenceDeductionMode: PayrollRuleMode
  absenceDeductionValue: number
  createdAt: string
  updatedAt: string
}

export interface PayrollAdjustmentDraft {
  type: PayrollAdjustmentType
  source: PayrollAdjustmentSource
  sourceReference: string | null
  reason: string
  amount: number
  isAutoGenerated: boolean
}

function toSettingsData(settings: {
  id: string
  academyId: string
  autoApplyLateDeductions: boolean
  lateGraceMinutes: number
  lateDeductionMode: PayrollRuleMode
  lateDeductionValue: unknown
  autoApplyAbsenceDeductions: boolean
  absenceDeductionMode: PayrollRuleMode
  absenceDeductionValue: unknown
  createdAt: Date
  updatedAt: Date
}): AcademyPayrollSettingsData {
  return {
    id: settings.id,
    academyId: settings.academyId,
    autoApplyLateDeductions: settings.autoApplyLateDeductions,
    lateGraceMinutes: settings.lateGraceMinutes,
    lateDeductionMode: settings.lateDeductionMode,
    lateDeductionValue: toNumber(settings.lateDeductionValue),
    autoApplyAbsenceDeductions: settings.autoApplyAbsenceDeductions,
    absenceDeductionMode: settings.absenceDeductionMode,
    absenceDeductionValue: toNumber(settings.absenceDeductionValue),
    createdAt: settings.createdAt.toISOString(),
    updatedAt: settings.updatedAt.toISOString(),
  }
}

export async function getOrCreateAcademyPayrollSettings(academyId: string) {
  const settings = await prisma.academyPayrollSettings.upsert({
    where: { academyId },
    update: {},
    create: { academyId },
  })

  return toSettingsData(settings)
}

function buildSessionLabel(input: { className: string; courseCode: string | null }) {
  if (input.courseCode) {
    return `${input.courseCode}: ${input.className}`
  }

  return input.className
}

function buildLateJoinReason(input: {
  sessionDate: Date
  className: string
  courseCode: string | null
  lateMinutes: number
}) {
  return `Late join for ${buildSessionLabel(input)} on ${input.sessionDate.toLocaleDateString()} (${input.lateMinutes} minute${input.lateMinutes === 1 ? "" : "s"} late)`
}

function buildAbsenceReason(input: {
  sessionDate: Date
  className: string
  courseCode: string | null
}) {
  return `No join recorded for ${buildSessionLabel(input)} on ${input.sessionDate.toLocaleDateString()}`
}

export async function buildAutomaticPayrollAdjustments(recordId: string) {
  const record = await prisma.payrollRecord.findUnique({
    where: { id: recordId },
    select: {
      id: true,
      academyId: true,
      payYear: true,
      payMonth: true,
      grossAmount: true,
      role: true,
      user: {
        select: {
          teacherProfile: {
            select: {
              id: true,
            },
          },
        },
      },
    },
  })

  if (!record) {
    return null
  }

  const settings = await getOrCreateAcademyPayrollSettings(record.academyId)

  if (record.role !== Role.teacher || !record.user.teacherProfile?.id) {
    return {
      settings,
      adjustments: [] as PayrollAdjustmentDraft[],
    }
  }

  const teacherProfileId = record.user.teacherProfile.id
  const { start, end } = getPayrollPeriodBounds(record.payYear, record.payMonth)
  const effectivePeriodEnd = new Date(Math.min(end.getTime(), Date.now()))
  const baseSalary = toNumber(record.grossAmount)
  const adjustments: PayrollAdjustmentDraft[] = []

  if (
    settings.autoApplyLateDeductions &&
    settings.lateDeductionValue > 0 &&
    effectivePeriodEnd.getTime() >= start.getTime()
  ) {
    const lateJoins = await prisma.teacherSessionJoin.findMany({
      where: {
        teacherProfileId,
        lateMinutes: {
          gt: settings.lateGraceMinutes,
        },
        classSession: {
          class: {
            academyId: record.academyId,
          },
          sessionDate: {
            gte: start,
            lte: effectivePeriodEnd,
          },
          status: {
            in: [SessionStatus.scheduled, SessionStatus.ongoing, SessionStatus.completed],
          },
        },
      },
      select: {
        classSessionId: true,
        lateMinutes: true,
        classSession: {
          select: {
            sessionDate: true,
            class: {
              select: {
                name: true,
                course: {
                  select: {
                    code: true,
                  },
                },
              },
            },
          },
        },
      },
    })

    for (const lateJoin of lateJoins) {
      const amount = calculatePayrollRuleAmount({
        baseAmount: baseSalary,
        mode: settings.lateDeductionMode,
        value: settings.lateDeductionValue,
      })

      if (amount <= 0) {
        continue
      }

      adjustments.push({
        type: PayrollAdjustmentType.deduction,
        source: PayrollAdjustmentSource.late_join,
        sourceReference: `session:${lateJoin.classSessionId}`,
        reason: buildLateJoinReason({
          sessionDate: lateJoin.classSession.sessionDate,
          className: lateJoin.classSession.class.name,
          courseCode: lateJoin.classSession.class.course.code,
          lateMinutes: lateJoin.lateMinutes,
        }),
        amount: roundPayrollAmount(amount),
        isAutoGenerated: true,
      })
    }
  }

  if (
    settings.autoApplyAbsenceDeductions &&
    settings.absenceDeductionValue > 0 &&
    effectivePeriodEnd.getTime() >= start.getTime()
  ) {
    const sessions = await prisma.classSession.findMany({
      where: {
        class: {
          academyId: record.academyId,
          teachers: {
            some: {
              teacherProfileId,
            },
          },
        },
        sessionDate: {
          gte: start,
          lte: effectivePeriodEnd,
        },
        status: {
          in: [SessionStatus.scheduled, SessionStatus.ongoing, SessionStatus.completed],
        },
      },
      select: {
        id: true,
        sessionDate: true,
        class: {
          select: {
            name: true,
            course: {
              select: {
                code: true,
              },
            },
          },
        },
        teacherJoins: {
          where: {
            teacherProfileId,
          },
          select: {
            id: true,
          },
        },
      },
    })

    for (const session of sessions) {
      if (session.teacherJoins.length > 0) {
        continue
      }

      const amount = calculatePayrollRuleAmount({
        baseAmount: baseSalary,
        mode: settings.absenceDeductionMode,
        value: settings.absenceDeductionValue,
      })

      if (amount <= 0) {
        continue
      }

      adjustments.push({
        type: PayrollAdjustmentType.deduction,
        source: PayrollAdjustmentSource.absence,
        sourceReference: `session:${session.id}`,
        reason: buildAbsenceReason({
          sessionDate: session.sessionDate,
          className: session.class.name,
          courseCode: session.class.course.code,
        }),
        amount: roundPayrollAmount(amount),
        isAutoGenerated: true,
      })
    }
  }

  return {
    settings,
    adjustments,
  }
}

export async function recalculateAutomaticPayrollAdjustments(input: {
  recordId: string
  actorUserId?: string | null
}) {
  const result = await buildAutomaticPayrollAdjustments(input.recordId)

  if (!result) {
    return null
  }

  await prisma.$transaction(async (tx) => {
    await tx.payrollAdjustment.deleteMany({
      where: {
        payrollRecordId: input.recordId,
        isAutoGenerated: true,
        source: {
          in: [PayrollAdjustmentSource.late_join, PayrollAdjustmentSource.absence],
        },
      },
    })

    for (const adjustment of result.adjustments) {
      await tx.payrollAdjustment.create({
        data: {
          payrollRecordId: input.recordId,
          type: adjustment.type,
          source: adjustment.source,
          sourceReference: adjustment.sourceReference,
          reason: adjustment.reason,
          amount: adjustment.amount,
          isAutoGenerated: true,
          createdByUserId: input.actorUserId || null,
        },
      })
    }

    await tx.payrollRecord.update({
      where: { id: input.recordId },
      data: {
        salarySlipUrl: null,
        updatedByUserId: input.actorUserId || undefined,
      },
    })
  })

  return result
}

export async function synchronizePayrollRecordWithAdjustments(input: {
  recordId: string
  actorUserId?: string | null
}) {
  const record = await prisma.payrollRecord.findUnique({
    where: {
      id: input.recordId,
    },
    select: {
      id: true,
      grossAmount: true,
      paidAmount: true,
      paymentDate: true,
      adjustments: {
        select: {
          type: true,
          amount: true,
        },
      },
    },
  })

  if (!record) {
    return null
  }

  const breakdown = calculatePayrollBreakdownTotals(
    toNumber(record.grossAmount),
    record.adjustments.map((adjustment) => ({
      type: adjustment.type,
      amount: toNumber(adjustment.amount),
    }))
  )

  const paidAmount = roundPayrollAmount(toNumber(record.paidAmount))

  let status: PayrollStatus = PayrollStatus.pending
  let paymentDate: Date | null = null

  if (breakdown.netPayable <= 0) {
    status = PayrollStatus.paid
    paymentDate = record.paymentDate || new Date()
  } else if (paidAmount <= 0) {
    status = PayrollStatus.pending
    paymentDate = null
  } else if (paidAmount >= breakdown.netPayable) {
    status = PayrollStatus.paid
    paymentDate = record.paymentDate || new Date()
  } else {
    status = PayrollStatus.partial
    paymentDate = record.paymentDate || null
  }

  await prisma.payrollRecord.update({
    where: {
      id: record.id,
    },
    data: {
      status,
      paymentDate,
      updatedByUserId: input.actorUserId || undefined,
    },
  })

  return {
    status,
    paymentDate: paymentDate?.toISOString() || null,
    netPayable: breakdown.netPayable,
    paidAmount,
  }
}

export async function getPayrollRecordPayableAmount(input: {
  recordId: string
  grossAmountOverride?: number
}) {
  const record = await prisma.payrollRecord.findUnique({
    where: {
      id: input.recordId,
    },
    select: {
      grossAmount: true,
      adjustments: {
        select: {
          type: true,
          amount: true,
        },
      },
    },
  })

  if (!record) {
    return null
  }

  const breakdown = calculatePayrollBreakdownTotals(
    input.grossAmountOverride ?? toNumber(record.grossAmount),
    record.adjustments.map((adjustment) => ({
      type: adjustment.type,
      amount: toNumber(adjustment.amount),
    }))
  )

  return breakdown.netPayable
}
