import { PayrollAdjustmentType, PayrollStatus, Prisma, Role } from "@prisma/client"
import { prisma } from "@/lib/prisma"
import {
  AcademyPayrollSettingsData,
  getOrCreateAcademyPayrollSettings,
} from "@/lib/payroll/payroll-adjustments"
import {
  PAYROLL_ELIGIBLE_ROLES,
  PayrollEligibleRole,
  calculatePayrollBreakdownTotals,
  formatPayrollPeriod,
  getRoleSortOrder,
  isPayrollStatus,
  parsePayrollMonth,
  payrollRoleLabels,
  roundPayrollAmount,
  toNumber,
} from "@/lib/payroll/payroll-utils"

export interface PayrollStaffOption {
  id: string
  firstName: string
  lastName: string
  email: string
  phone: string | null
  avatarUrl: string | null
  role: "admin" | "teacher"
  isActive: boolean
  employeeId: string | null
  compensationProfile: {
    id: string
    amount: number
    currency: string
    isActive: boolean
    effectiveFrom: string
    notes: string | null
  } | null
}

export interface CompensationProfileListItem {
  id: string
  amount: number
  currency: string
  effectiveFrom: string
  notes: string | null
  isActive: boolean
  createdAt: string
  updatedAt: string
  payrollRecordsCount: number
  lastPayrollRecord: {
    id: string
    payYear: number
    payMonth: number
    periodLabel: string
    status: PayrollStatus
    currency: string
    netPayable: number
    isFinalized: boolean
  } | null
  user: Omit<PayrollStaffOption, "compensationProfile">
}

export interface PayrollAdjustmentListItem {
  id: string
  type: PayrollAdjustmentType
  source: string
  sourceReference: string | null
  reason: string
  amount: number
  isAutoGenerated: boolean
  createdAt: string
  updatedAt: string
  createdBy: {
    firstName: string
    lastName: string
  } | null
  updatedBy: {
    firstName: string
    lastName: string
  } | null
}

export interface PayrollBreakdownSummary {
  baseSalary: number
  totalBonuses: number
  totalDeductions: number
  totalAdvanceAdjustments: number
  totalAdjustments: number
  netPayable: number
}

export interface PayrollRecordListItem {
  id: string
  payYear: number
  payMonth: number
  periodLabel: string
  role: "admin" | "teacher"
  status: PayrollStatus
  grossAmount: number
  paidAmount: number
  outstandingAmount: number
  currency: string
  paymentDate: string | null
  notes: string | null
  salarySlipUrl: string | null
  isFinalized: boolean
  finalizedAt: string | null
  createdAt: string
  updatedAt: string
  adjustmentCount: number
  breakdown: PayrollBreakdownSummary
  user: Omit<PayrollStaffOption, "compensationProfile">
  staffCompensationProfile: {
    id: string
    amount: number
    currency: string
    isActive: boolean
  }
  createdBy: {
    firstName: string
    lastName: string
  }
  updatedBy: {
    firstName: string
    lastName: string
  } | null
  finalizedBy: {
    firstName: string
    lastName: string
  } | null
}

export interface PayrollRecordDetailItem extends PayrollRecordListItem {
  compensationProfile: {
    id: string
    amount: number
    currency: string
    effectiveFrom: string
    notes: string | null
    isActive: boolean
    createdAt: string
    updatedAt: string
  }
  adjustments: PayrollAdjustmentListItem[]
}

export interface PayrollSummaryTotals {
  totalRecords: number
  pendingCount: number
  partialCount: number
  paidCount: number
  finalizedCount: number
  baseByCurrency: Array<{
    currency: string
    amount: number
  }>
  netByCurrency: Array<{
    currency: string
    amount: number
  }>
  paidByCurrency: Array<{
    currency: string
    amount: number
  }>
  outstandingByCurrency: Array<{
    currency: string
    amount: number
  }>
  bonusesByCurrency: Array<{
    currency: string
    amount: number
  }>
  deductionsByCurrency: Array<{
    currency: string
    amount: number
  }>
  advancesByCurrency: Array<{
    currency: string
    amount: number
  }>
}

export interface AdminPayrollListData {
  records: PayrollRecordListItem[]
  total: number
  page: number
  totalPages: number
  summary: PayrollSummaryTotals
}

export interface AdminPayrollRecordDetailData {
  record: PayrollRecordDetailItem
  history: PayrollRecordListItem[]
  settings: AcademyPayrollSettingsData
}

export interface TeacherPayrollPageData {
  staffMember: Omit<PayrollStaffOption, "compensationProfile"> | null
  compensationProfile: CompensationProfileListItem | null
  records: PayrollRecordListItem[]
  summary: PayrollSummaryTotals
}

export interface TeacherPayrollRecordDetailData {
  record: PayrollRecordDetailItem
  history: PayrollRecordListItem[]
}

type PayrollFilters = {
  academyId: string
  page: number
  limit: number
  role?: "admin" | "teacher"
  userId?: string
  month?: string
  status?: PayrollStatus
}

function buildStaffWhere(
  academyId: string,
  includeUserIds: string[] = []
): Prisma.UserWhereInput {
  const uniqueIncludedUserIds = Array.from(
    new Set(includeUserIds.filter(Boolean))
  )

  return {
    academyId,
    role: {
      in: [...PAYROLL_ELIGIBLE_ROLES],
    },
    OR: [
      {
        isActive: true,
      },
      ...(uniqueIncludedUserIds.length > 0
        ? [
            {
              id: {
                in: uniqueIncludedUserIds,
              },
            },
          ]
        : []),
    ],
  }
}

function buildRecordWhere(filters: PayrollFilters): Prisma.PayrollRecordWhereInput {
  const month = parsePayrollMonth(filters.month)

  return {
    academyId: filters.academyId,
    ...(filters.role
      ? {
          role: filters.role,
        }
      : {}),
    ...(filters.userId
      ? {
          userId: filters.userId,
        }
      : {}),
    ...(filters.status
      ? {
          status: filters.status,
        }
      : {}),
    ...(month
      ? {
          payYear: month.payYear,
          payMonth: month.payMonth,
        }
      : {}),
  }
}

function buildProfileWhere(input: {
  academyId: string
  role?: "admin" | "teacher"
  userId?: string
}): Prisma.StaffCompensationProfileWhereInput {
  return {
    academyId: input.academyId,
    ...(input.userId
      ? {
          userId: input.userId,
        }
      : {}),
    ...(input.role
      ? {
          user: {
            role: input.role,
          },
        }
      : {}),
  }
}

function toBaseStaffMember(
  user: {
    id: string
    firstName: string
    lastName: string
    email: string
    phone: string | null
    avatarUrl: string | null
    role: Role
    isActive: boolean
    teacherProfile: {
      employeeId: string | null
    } | null
  }
): Omit<PayrollStaffOption, "compensationProfile"> {
  return {
    id: user.id,
    firstName: user.firstName,
    lastName: user.lastName,
    email: user.email,
    phone: user.phone,
    avatarUrl: user.avatarUrl,
    role: user.role as PayrollEligibleRole,
    isActive: user.isActive,
    employeeId: user.teacherProfile?.employeeId || null,
  }
}

function toPayrollAdjustmentItem(adjustment: {
  id: string
  type: PayrollAdjustmentType
  source: string
  sourceReference: string | null
  reason: string
  amount: Prisma.Decimal
  isAutoGenerated: boolean
  createdAt: Date
  updatedAt: Date
  createdBy: {
    firstName: string
    lastName: string
  } | null
  updatedBy: {
    firstName: string
    lastName: string
  } | null
}): PayrollAdjustmentListItem {
  return {
    id: adjustment.id,
    type: adjustment.type,
    source: adjustment.source,
    sourceReference: adjustment.sourceReference,
    reason: adjustment.reason,
    amount: roundPayrollAmount(toNumber(adjustment.amount)),
    isAutoGenerated: adjustment.isAutoGenerated,
    createdAt: adjustment.createdAt.toISOString(),
    updatedAt: adjustment.updatedAt.toISOString(),
    createdBy: adjustment.createdBy,
    updatedBy: adjustment.updatedBy,
  }
}

function buildBreakdownSummary(
  grossAmount: Prisma.Decimal | number,
  paidAmount: Prisma.Decimal | number,
  adjustments: Array<{
    type: PayrollAdjustmentType
    amount: Prisma.Decimal | number
  }>
) {
  const breakdown = calculatePayrollBreakdownTotals(
    toNumber(grossAmount),
    adjustments.map((adjustment) => ({
      type: adjustment.type,
      amount: toNumber(adjustment.amount),
    }))
  )

  const outstandingAmount = roundPayrollAmount(
    Math.max(breakdown.netPayable - toNumber(paidAmount), 0)
  )

  return {
    breakdown,
    outstandingAmount,
  }
}

function mapCurrencyTotals(source: Map<string, number>) {
  return Array.from(source.entries())
    .map(([currency, amount]) => ({
      currency,
      amount: roundPayrollAmount(amount),
    }))
    .sort((left, right) => left.currency.localeCompare(right.currency))
}

function summarizeRecords(
  records: Array<{
    grossAmount: Prisma.Decimal | number
    paidAmount: Prisma.Decimal | number
    currency: string
    status: PayrollStatus
    isFinalized: boolean
    adjustments: Array<{
      type: PayrollAdjustmentType
      amount: Prisma.Decimal | number
    }>
  }>
): PayrollSummaryTotals {
  const baseByCurrency = new Map<string, number>()
  const netByCurrency = new Map<string, number>()
  const paidByCurrency = new Map<string, number>()
  const outstandingByCurrency = new Map<string, number>()
  const bonusesByCurrency = new Map<string, number>()
  const deductionsByCurrency = new Map<string, number>()
  const advancesByCurrency = new Map<string, number>()

  const summary: PayrollSummaryTotals = {
    totalRecords: records.length,
    pendingCount: 0,
    partialCount: 0,
    paidCount: 0,
    finalizedCount: 0,
    baseByCurrency: [],
    netByCurrency: [],
    paidByCurrency: [],
    outstandingByCurrency: [],
    bonusesByCurrency: [],
    deductionsByCurrency: [],
    advancesByCurrency: [],
  }

  for (const record of records) {
    const currency = record.currency
    const { breakdown, outstandingAmount } = buildBreakdownSummary(
      record.grossAmount,
      record.paidAmount,
      record.adjustments
    )

    baseByCurrency.set(
      currency,
      (baseByCurrency.get(currency) || 0) + breakdown.baseSalary
    )
    netByCurrency.set(
      currency,
      (netByCurrency.get(currency) || 0) + breakdown.netPayable
    )
    paidByCurrency.set(
      currency,
      (paidByCurrency.get(currency) || 0) + toNumber(record.paidAmount)
    )
    outstandingByCurrency.set(
      currency,
      (outstandingByCurrency.get(currency) || 0) + outstandingAmount
    )
    bonusesByCurrency.set(
      currency,
      (bonusesByCurrency.get(currency) || 0) + breakdown.totalBonuses
    )
    deductionsByCurrency.set(
      currency,
      (deductionsByCurrency.get(currency) || 0) + breakdown.totalDeductions
    )
    advancesByCurrency.set(
      currency,
      (advancesByCurrency.get(currency) || 0) +
        breakdown.totalAdvanceAdjustments
    )

    if (record.status === PayrollStatus.pending) {
      summary.pendingCount += 1
    } else if (record.status === PayrollStatus.partial) {
      summary.partialCount += 1
    } else {
      summary.paidCount += 1
    }

    if (record.isFinalized) {
      summary.finalizedCount += 1
    }
  }

  summary.baseByCurrency = mapCurrencyTotals(baseByCurrency)
  summary.netByCurrency = mapCurrencyTotals(netByCurrency)
  summary.paidByCurrency = mapCurrencyTotals(paidByCurrency)
  summary.outstandingByCurrency = mapCurrencyTotals(outstandingByCurrency)
  summary.bonusesByCurrency = mapCurrencyTotals(bonusesByCurrency)
  summary.deductionsByCurrency = mapCurrencyTotals(deductionsByCurrency)
  summary.advancesByCurrency = mapCurrencyTotals(advancesByCurrency)

  return summary
}

function toPayrollRecordListItem(record: {
  id: string
  payYear: number
  payMonth: number
  role: Role
  status: PayrollStatus
  grossAmount: Prisma.Decimal
  paidAmount: Prisma.Decimal
  currency: string
  paymentDate: Date | null
  notes: string | null
  salarySlipUrl: string | null
  isFinalized: boolean
  finalizedAt: Date | null
  createdAt: Date
  updatedAt: Date
  user: {
    id: string
    firstName: string
    lastName: string
    email: string
    phone: string | null
    avatarUrl: string | null
    role: Role
    isActive: boolean
    teacherProfile: {
      employeeId: string | null
    } | null
  }
  staffCompensationProfile: {
    id: string
    amount: Prisma.Decimal
    currency: string
    isActive: boolean
  }
  adjustments: Array<{
    id: string
    type: PayrollAdjustmentType
    source: string
    sourceReference: string | null
    reason: string
    amount: Prisma.Decimal
    isAutoGenerated: boolean
    createdAt: Date
    updatedAt: Date
    createdBy: {
      firstName: string
      lastName: string
    } | null
    updatedBy: {
      firstName: string
      lastName: string
    } | null
  }>
  createdBy: {
    firstName: string
    lastName: string
  }
  updatedBy: {
    firstName: string
    lastName: string
  } | null
  finalizedBy: {
    firstName: string
    lastName: string
  } | null
}): PayrollRecordListItem {
  const { breakdown, outstandingAmount } = buildBreakdownSummary(
    record.grossAmount,
    record.paidAmount,
    record.adjustments
  )

  return {
    id: record.id,
    payYear: record.payYear,
    payMonth: record.payMonth,
    periodLabel: formatPayrollPeriod(record.payYear, record.payMonth),
    role: record.role as PayrollEligibleRole,
    status: record.status,
    grossAmount: roundPayrollAmount(toNumber(record.grossAmount)),
    paidAmount: roundPayrollAmount(toNumber(record.paidAmount)),
    outstandingAmount,
    currency: record.currency,
    paymentDate: record.paymentDate?.toISOString() || null,
    notes: record.notes,
    salarySlipUrl: record.salarySlipUrl,
    isFinalized: record.isFinalized,
    finalizedAt: record.finalizedAt?.toISOString() || null,
    createdAt: record.createdAt.toISOString(),
    updatedAt: record.updatedAt.toISOString(),
    adjustmentCount: record.adjustments.length,
    breakdown,
    user: toBaseStaffMember(record.user),
    staffCompensationProfile: {
      id: record.staffCompensationProfile.id,
      amount: roundPayrollAmount(toNumber(record.staffCompensationProfile.amount)),
      currency: record.staffCompensationProfile.currency,
      isActive: record.staffCompensationProfile.isActive,
    },
    createdBy: record.createdBy,
    updatedBy: record.updatedBy,
    finalizedBy: record.finalizedBy,
  }
}

export async function getPayrollStaffOptions(
  academyId: string,
  includeUserIds: string[] = []
): Promise<PayrollStaffOption[]> {
  const users = await prisma.user.findMany({
    where: buildStaffWhere(academyId, includeUserIds),
    select: {
      id: true,
      firstName: true,
      lastName: true,
      email: true,
      phone: true,
      avatarUrl: true,
      role: true,
      isActive: true,
      teacherProfile: {
        select: {
          employeeId: true,
        },
      },
      compensationProfile: {
        select: {
          id: true,
          amount: true,
          currency: true,
          isActive: true,
          effectiveFrom: true,
          notes: true,
        },
      },
    },
  })

  return users
    .filter((user) => user.role === Role.admin || user.role === Role.teacher)
    .map((user) => ({
      ...toBaseStaffMember(user),
      compensationProfile: user.compensationProfile
        ? {
            id: user.compensationProfile.id,
            amount: roundPayrollAmount(toNumber(user.compensationProfile.amount)),
            currency: user.compensationProfile.currency,
            isActive: user.compensationProfile.isActive,
            effectiveFrom: user.compensationProfile.effectiveFrom.toISOString(),
            notes: user.compensationProfile.notes,
          }
        : null,
    }))
    .sort((left, right) => {
      if (left.isActive !== right.isActive) {
        return left.isActive ? -1 : 1
      }

      if (left.role !== right.role) {
        return getRoleSortOrder(left.role) - getRoleSortOrder(right.role)
      }

      const firstNameComparison = left.firstName.localeCompare(right.firstName)

      if (firstNameComparison !== 0) {
        return firstNameComparison
      }

      return left.lastName.localeCompare(right.lastName)
    })
}

export async function getCompensationProfiles(input: {
  academyId: string
  role?: "admin" | "teacher"
  userId?: string
}): Promise<CompensationProfileListItem[]> {
  const profiles = await prisma.staffCompensationProfile.findMany({
    where: buildProfileWhere(input),
    select: {
      id: true,
      amount: true,
      currency: true,
      effectiveFrom: true,
      notes: true,
      isActive: true,
      createdAt: true,
      updatedAt: true,
      user: {
        select: {
          id: true,
          firstName: true,
          lastName: true,
          email: true,
          phone: true,
          avatarUrl: true,
          role: true,
          isActive: true,
          teacherProfile: {
            select: {
              employeeId: true,
            },
          },
        },
      },
      payrollRecords: {
        select: {
          id: true,
          payYear: true,
          payMonth: true,
          status: true,
          currency: true,
          isFinalized: true,
          grossAmount: true,
          adjustments: {
            select: {
              type: true,
              amount: true,
            },
          },
        },
        orderBy: [
          {
            payYear: "desc",
          },
          {
            payMonth: "desc",
          },
          {
            createdAt: "desc",
          },
        ],
        take: 1,
      },
      _count: {
        select: {
          payrollRecords: true,
        },
      },
    },
    orderBy: [
      {
        isActive: "desc",
      },
      {
        user: {
          firstName: "asc",
        },
      },
      {
        user: {
          lastName: "asc",
        },
      },
    ],
  })

  return profiles.map((profile) => ({
    id: profile.id,
    amount: roundPayrollAmount(toNumber(profile.amount)),
    currency: profile.currency,
    effectiveFrom: profile.effectiveFrom.toISOString(),
    notes: profile.notes,
    isActive: profile.isActive,
    createdAt: profile.createdAt.toISOString(),
    updatedAt: profile.updatedAt.toISOString(),
    payrollRecordsCount: profile._count.payrollRecords,
    lastPayrollRecord: profile.payrollRecords[0]
      ? {
          id: profile.payrollRecords[0].id,
          payYear: profile.payrollRecords[0].payYear,
          payMonth: profile.payrollRecords[0].payMonth,
          periodLabel: formatPayrollPeriod(
            profile.payrollRecords[0].payYear,
            profile.payrollRecords[0].payMonth
          ),
          status: profile.payrollRecords[0].status,
          currency: profile.payrollRecords[0].currency,
          netPayable: calculatePayrollBreakdownTotals(
            toNumber(profile.payrollRecords[0].grossAmount),
            profile.payrollRecords[0].adjustments.map((adjustment) => ({
              type: adjustment.type,
              amount: toNumber(adjustment.amount),
            }))
          ).netPayable,
          isFinalized: profile.payrollRecords[0].isFinalized,
        }
      : null,
    user: toBaseStaffMember(profile.user),
  }))
}

export async function getAdminPayrollList(
  input: PayrollFilters
): Promise<AdminPayrollListData> {
  const where = buildRecordWhere(input)

  const [records, total, summaryRecords] = await Promise.all([
    prisma.payrollRecord.findMany({
      where,
      select: {
        id: true,
        payYear: true,
        payMonth: true,
        role: true,
        status: true,
        grossAmount: true,
        paidAmount: true,
        currency: true,
        paymentDate: true,
        notes: true,
        salarySlipUrl: true,
        isFinalized: true,
        finalizedAt: true,
        createdAt: true,
        updatedAt: true,
        user: {
          select: {
            id: true,
            firstName: true,
            lastName: true,
            email: true,
            phone: true,
            avatarUrl: true,
            role: true,
            isActive: true,
            teacherProfile: {
              select: {
                employeeId: true,
              },
            },
          },
        },
        staffCompensationProfile: {
          select: {
            id: true,
            amount: true,
            currency: true,
            isActive: true,
          },
        },
        adjustments: {
          select: {
            id: true,
            type: true,
            source: true,
            sourceReference: true,
            reason: true,
            amount: true,
            isAutoGenerated: true,
            createdAt: true,
            updatedAt: true,
            createdBy: {
              select: {
                firstName: true,
                lastName: true,
              },
            },
            updatedBy: {
              select: {
                firstName: true,
                lastName: true,
              },
            },
          },
        },
        createdBy: {
          select: {
            firstName: true,
            lastName: true,
          },
        },
        updatedBy: {
          select: {
            firstName: true,
            lastName: true,
          },
        },
        finalizedBy: {
          select: {
            firstName: true,
            lastName: true,
          },
        },
      },
      orderBy: [
        {
          payYear: "desc",
        },
        {
          payMonth: "desc",
        },
        {
          createdAt: "desc",
        },
      ],
      skip: (input.page - 1) * input.limit,
      take: input.limit,
    }),
    prisma.payrollRecord.count({ where }),
    prisma.payrollRecord.findMany({
      where,
      select: {
        grossAmount: true,
        paidAmount: true,
        currency: true,
        status: true,
        isFinalized: true,
        adjustments: {
          select: {
            type: true,
            amount: true,
          },
        },
      },
    }),
  ])

  return {
    records: records.map(toPayrollRecordListItem),
    total,
    page: input.page,
    totalPages: Math.ceil(total / input.limit),
    summary: summarizeRecords(summaryRecords),
  }
}

export async function getAdminPayrollRecordDetail(
  academyId: string,
  recordId: string
): Promise<AdminPayrollRecordDetailData | null> {
  const record = await prisma.payrollRecord.findFirst({
    where: {
      id: recordId,
      academyId,
    },
    select: {
      id: true,
      payYear: true,
      payMonth: true,
      role: true,
      status: true,
      grossAmount: true,
      paidAmount: true,
      currency: true,
      paymentDate: true,
      notes: true,
      salarySlipUrl: true,
      isFinalized: true,
      finalizedAt: true,
      createdAt: true,
      updatedAt: true,
      user: {
        select: {
          id: true,
          firstName: true,
          lastName: true,
          email: true,
          phone: true,
          avatarUrl: true,
          role: true,
          isActive: true,
          teacherProfile: {
            select: {
              employeeId: true,
            },
          },
        },
      },
      staffCompensationProfile: {
        select: {
          id: true,
          amount: true,
          currency: true,
          effectiveFrom: true,
          notes: true,
          isActive: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      adjustments: {
        orderBy: [
          {
            type: "asc",
          },
          {
            createdAt: "asc",
          },
        ],
        select: {
          id: true,
          type: true,
          source: true,
          sourceReference: true,
          reason: true,
          amount: true,
          isAutoGenerated: true,
          createdAt: true,
          updatedAt: true,
          createdBy: {
            select: {
              firstName: true,
              lastName: true,
            },
          },
          updatedBy: {
            select: {
              firstName: true,
              lastName: true,
            },
          },
        },
      },
      createdBy: {
        select: {
          firstName: true,
          lastName: true,
        },
      },
      updatedBy: {
        select: {
          firstName: true,
          lastName: true,
        },
      },
      finalizedBy: {
        select: {
          firstName: true,
          lastName: true,
        },
      },
    },
  })

  if (!record) {
    return null
  }

  const [history, settings] = await Promise.all([
    prisma.payrollRecord.findMany({
      where: {
        academyId,
        userId: record.user.id,
      },
      select: {
        id: true,
        payYear: true,
        payMonth: true,
        role: true,
        status: true,
        grossAmount: true,
        paidAmount: true,
        currency: true,
        paymentDate: true,
        notes: true,
        salarySlipUrl: true,
        isFinalized: true,
        finalizedAt: true,
        createdAt: true,
        updatedAt: true,
        user: {
          select: {
            id: true,
            firstName: true,
            lastName: true,
            email: true,
            phone: true,
            avatarUrl: true,
            role: true,
            isActive: true,
            teacherProfile: {
              select: {
                employeeId: true,
              },
            },
          },
        },
        staffCompensationProfile: {
          select: {
            id: true,
            amount: true,
            currency: true,
            isActive: true,
          },
        },
        adjustments: {
          select: {
            id: true,
            type: true,
            source: true,
            sourceReference: true,
            reason: true,
            amount: true,
            isAutoGenerated: true,
            createdAt: true,
            updatedAt: true,
            createdBy: {
              select: {
                firstName: true,
                lastName: true,
              },
            },
            updatedBy: {
              select: {
                firstName: true,
                lastName: true,
              },
            },
          },
        },
        createdBy: {
          select: {
            firstName: true,
            lastName: true,
          },
        },
        updatedBy: {
          select: {
            firstName: true,
            lastName: true,
          },
        },
        finalizedBy: {
          select: {
            firstName: true,
            lastName: true,
          },
        },
      },
      orderBy: [
        {
          payYear: "desc",
        },
        {
          payMonth: "desc",
        },
      ],
      take: 12,
    }),
    getOrCreateAcademyPayrollSettings(academyId),
  ])

  const recordListItem = toPayrollRecordListItem(record)

  return {
    record: {
      ...recordListItem,
      compensationProfile: {
        id: record.staffCompensationProfile.id,
        amount: roundPayrollAmount(toNumber(record.staffCompensationProfile.amount)),
        currency: record.staffCompensationProfile.currency,
        effectiveFrom: record.staffCompensationProfile.effectiveFrom.toISOString(),
        notes: record.staffCompensationProfile.notes,
        isActive: record.staffCompensationProfile.isActive,
        createdAt: record.staffCompensationProfile.createdAt.toISOString(),
        updatedAt: record.staffCompensationProfile.updatedAt.toISOString(),
      },
      adjustments: record.adjustments.map(toPayrollAdjustmentItem),
    },
    history: history.map(toPayrollRecordListItem),
    settings,
  }
}

export async function getTeacherPayrollPageData(
  academyId: string,
  userId: string
): Promise<TeacherPayrollPageData> {
  const user = await prisma.user.findFirst({
    where: {
      id: userId,
      academyId,
      role: Role.teacher,
    },
    select: {
      id: true,
      firstName: true,
      lastName: true,
      email: true,
      phone: true,
      avatarUrl: true,
      role: true,
      isActive: true,
      teacherProfile: {
        select: {
          employeeId: true,
        },
      },
      compensationProfile: {
        select: {
          id: true,
          amount: true,
          currency: true,
          effectiveFrom: true,
          notes: true,
          isActive: true,
          createdAt: true,
          updatedAt: true,
          _count: {
            select: {
              payrollRecords: true,
            },
          },
          payrollRecords: {
            select: {
              id: true,
              payYear: true,
              payMonth: true,
              status: true,
              currency: true,
              isFinalized: true,
              grossAmount: true,
              adjustments: {
                select: {
                  type: true,
                  amount: true,
                },
              },
            },
            orderBy: [
              {
                payYear: "desc",
              },
              {
                payMonth: "desc",
              },
              {
                createdAt: "desc",
              },
            ],
            take: 1,
          },
        },
      },
    },
  })

  if (!user) {
    return {
      staffMember: null,
      compensationProfile: null,
      records: [],
      summary: summarizeRecords([]),
    }
  }

  const records = await prisma.payrollRecord.findMany({
    where: {
      academyId,
      userId,
    },
    select: {
      id: true,
      payYear: true,
      payMonth: true,
      role: true,
      status: true,
      grossAmount: true,
      paidAmount: true,
      currency: true,
      paymentDate: true,
      notes: true,
      salarySlipUrl: true,
      isFinalized: true,
      finalizedAt: true,
      createdAt: true,
      updatedAt: true,
      user: {
        select: {
          id: true,
          firstName: true,
          lastName: true,
          email: true,
          phone: true,
          avatarUrl: true,
          role: true,
          isActive: true,
          teacherProfile: {
            select: {
              employeeId: true,
            },
          },
        },
      },
      staffCompensationProfile: {
        select: {
          id: true,
          amount: true,
          currency: true,
          isActive: true,
        },
      },
      adjustments: {
        select: {
          id: true,
          type: true,
          source: true,
          sourceReference: true,
          reason: true,
          amount: true,
          isAutoGenerated: true,
          createdAt: true,
          updatedAt: true,
          createdBy: {
            select: {
              firstName: true,
              lastName: true,
            },
          },
          updatedBy: {
            select: {
              firstName: true,
              lastName: true,
            },
          },
        },
      },
      createdBy: {
        select: {
          firstName: true,
          lastName: true,
        },
      },
      updatedBy: {
        select: {
          firstName: true,
          lastName: true,
        },
      },
      finalizedBy: {
        select: {
          firstName: true,
          lastName: true,
        },
      },
    },
    orderBy: [
      {
        payYear: "desc",
      },
      {
        payMonth: "desc",
      },
      {
        createdAt: "desc",
      },
    ],
  })

  return {
    staffMember: toBaseStaffMember(user),
    compensationProfile: user.compensationProfile
      ? {
          id: user.compensationProfile.id,
          amount: roundPayrollAmount(toNumber(user.compensationProfile.amount)),
          currency: user.compensationProfile.currency,
          effectiveFrom: user.compensationProfile.effectiveFrom.toISOString(),
          notes: user.compensationProfile.notes,
          isActive: user.compensationProfile.isActive,
          createdAt: user.compensationProfile.createdAt.toISOString(),
          updatedAt: user.compensationProfile.updatedAt.toISOString(),
          payrollRecordsCount: user.compensationProfile._count.payrollRecords,
          lastPayrollRecord: user.compensationProfile.payrollRecords[0]
            ? {
                id: user.compensationProfile.payrollRecords[0].id,
                payYear: user.compensationProfile.payrollRecords[0].payYear,
                payMonth: user.compensationProfile.payrollRecords[0].payMonth,
                periodLabel: formatPayrollPeriod(
                  user.compensationProfile.payrollRecords[0].payYear,
                  user.compensationProfile.payrollRecords[0].payMonth
                ),
                status: user.compensationProfile.payrollRecords[0].status,
                currency: user.compensationProfile.payrollRecords[0].currency,
                netPayable: calculatePayrollBreakdownTotals(
                  toNumber(user.compensationProfile.payrollRecords[0].grossAmount),
                  user.compensationProfile.payrollRecords[0].adjustments.map(
                    (adjustment) => ({
                      type: adjustment.type,
                      amount: toNumber(adjustment.amount),
                    })
                  )
                ).netPayable,
                isFinalized: user.compensationProfile.payrollRecords[0].isFinalized,
              }
            : null,
          user: toBaseStaffMember(user),
        }
      : null,
    records: records.map(toPayrollRecordListItem),
    summary: summarizeRecords(records),
  }
}

export async function getTeacherPayrollRecordDetail(input: {
  academyId: string
  userId: string
  recordId: string
}): Promise<TeacherPayrollRecordDetailData | null> {
  const record = await prisma.payrollRecord.findFirst({
    where: {
      id: input.recordId,
      academyId: input.academyId,
      userId: input.userId,
    },
    select: {
      id: true,
      payYear: true,
      payMonth: true,
      role: true,
      status: true,
      grossAmount: true,
      paidAmount: true,
      currency: true,
      paymentDate: true,
      notes: true,
      salarySlipUrl: true,
      isFinalized: true,
      finalizedAt: true,
      createdAt: true,
      updatedAt: true,
      user: {
        select: {
          id: true,
          firstName: true,
          lastName: true,
          email: true,
          phone: true,
          avatarUrl: true,
          role: true,
          isActive: true,
          teacherProfile: {
            select: {
              employeeId: true,
            },
          },
        },
      },
      staffCompensationProfile: {
        select: {
          id: true,
          amount: true,
          currency: true,
          effectiveFrom: true,
          notes: true,
          isActive: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      adjustments: {
        orderBy: [
          {
            type: "asc",
          },
          {
            createdAt: "asc",
          },
        ],
        select: {
          id: true,
          type: true,
          source: true,
          sourceReference: true,
          reason: true,
          amount: true,
          isAutoGenerated: true,
          createdAt: true,
          updatedAt: true,
          createdBy: {
            select: {
              firstName: true,
              lastName: true,
            },
          },
          updatedBy: {
            select: {
              firstName: true,
              lastName: true,
            },
          },
        },
      },
      createdBy: {
        select: {
          firstName: true,
          lastName: true,
        },
      },
      updatedBy: {
        select: {
          firstName: true,
          lastName: true,
        },
      },
      finalizedBy: {
        select: {
          firstName: true,
          lastName: true,
        },
      },
    },
  })

  if (!record) {
    return null
  }

  const history = await prisma.payrollRecord.findMany({
    where: {
      academyId: input.academyId,
      userId: input.userId,
    },
    select: {
      id: true,
      payYear: true,
      payMonth: true,
      role: true,
      status: true,
      grossAmount: true,
      paidAmount: true,
      currency: true,
      paymentDate: true,
      notes: true,
      salarySlipUrl: true,
      isFinalized: true,
      finalizedAt: true,
      createdAt: true,
      updatedAt: true,
      user: {
        select: {
          id: true,
          firstName: true,
          lastName: true,
          email: true,
          phone: true,
          avatarUrl: true,
          role: true,
          isActive: true,
          teacherProfile: {
            select: {
              employeeId: true,
            },
          },
        },
      },
      staffCompensationProfile: {
        select: {
          id: true,
          amount: true,
          currency: true,
          isActive: true,
        },
      },
      adjustments: {
        select: {
          id: true,
          type: true,
          source: true,
          sourceReference: true,
          reason: true,
          amount: true,
          isAutoGenerated: true,
          createdAt: true,
          updatedAt: true,
          createdBy: {
            select: {
              firstName: true,
              lastName: true,
            },
          },
          updatedBy: {
            select: {
              firstName: true,
              lastName: true,
            },
          },
        },
      },
      createdBy: {
        select: {
          firstName: true,
          lastName: true,
        },
      },
      updatedBy: {
        select: {
          firstName: true,
          lastName: true,
        },
      },
      finalizedBy: {
        select: {
          firstName: true,
          lastName: true,
        },
      },
    },
    orderBy: [
      {
        payYear: "desc",
      },
      {
        payMonth: "desc",
      },
    ],
    take: 12,
  })

  return {
    record: {
      ...toPayrollRecordListItem(record),
      compensationProfile: {
        id: record.staffCompensationProfile.id,
        amount: roundPayrollAmount(toNumber(record.staffCompensationProfile.amount)),
        currency: record.staffCompensationProfile.currency,
        effectiveFrom: record.staffCompensationProfile.effectiveFrom.toISOString(),
        notes: record.staffCompensationProfile.notes,
        isActive: record.staffCompensationProfile.isActive,
        createdAt: record.staffCompensationProfile.createdAt.toISOString(),
        updatedAt: record.staffCompensationProfile.updatedAt.toISOString(),
      },
      adjustments: record.adjustments.map(toPayrollAdjustmentItem),
    },
    history: history.map(toPayrollRecordListItem),
  }
}

export function getPayrollMonthOptions() {
  const today = new Date()

  return Array.from({ length: 12 }).map((_, index) => {
    const date = new Date(today.getFullYear(), today.getMonth() - index, 1)
    const value = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`

    return {
      value,
      label: formatPayrollPeriod(date.getFullYear(), date.getMonth() + 1),
    }
  })
}

export function getPayrollRoleOptions() {
  return PAYROLL_ELIGIBLE_ROLES.map((role) => ({
    value: role,
    label: payrollRoleLabels[role],
  }))
}

export function parsePayrollStatusFilter(value: string | undefined) {
  return value && isPayrollStatus(value) ? value : undefined
}
