"use client"

import { useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import {
  PayrollAdjustmentSource,
  PayrollAdjustmentType,
} from "@prisma/client"
import { Loader2, Pencil, PlusCircle, RefreshCcw, Trash2 } from "lucide-react"
import { PayrollAdjustmentListItem } from "@/lib/payroll/payroll-data"
import {
  payrollAdjustmentSourceLabels,
  payrollAdjustmentTypeLabels,
} from "@/lib/payroll/payroll-utils"
import { Button } from "@/components/ui/button"
import { CurrencyAmount } from "@/components/ui/currency-amount"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Textarea } from "@/components/ui/textarea"

interface AdjustmentFormState {
  type: PayrollAdjustmentType
  source: PayrollAdjustmentSource
  reason: string
  amount: string
}

interface PayrollAdjustmentsManagerProps {
  recordId: string
  adjustments: PayrollAdjustmentListItem[]
  currency: string
  canManage?: boolean
}

const defaultAdjustmentForm: AdjustmentFormState = {
  type: PayrollAdjustmentType.bonus,
  source: PayrollAdjustmentSource.manual,
  reason: "",
  amount: "",
}

export function PayrollAdjustmentsManager({
  recordId,
  adjustments,
  currency,
  canManage = false,
}: PayrollAdjustmentsManagerProps) {
  const router = useRouter()
  const [formState, setFormState] = useState<AdjustmentFormState>(defaultAdjustmentForm)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [isRecalculating, setIsRecalculating] = useState(false)
  const [errorMessage, setErrorMessage] = useState<string | null>(null)
  const [successMessage, setSuccessMessage] = useState<string | null>(null)

  const manualAdjustments = useMemo(
    () => adjustments.filter((adjustment) => !adjustment.isAutoGenerated),
    [adjustments]
  )

  function resetForm() {
    setEditingId(null)
    setFormState(defaultAdjustmentForm)
  }

  function startEdit(adjustment: PayrollAdjustmentListItem) {
    setEditingId(adjustment.id)
    setFormState({
      type: adjustment.type,
      source: adjustment.source as PayrollAdjustmentSource,
      reason: adjustment.reason,
      amount: adjustment.amount.toFixed(2),
    })
    setErrorMessage(null)
    setSuccessMessage(null)
  }

  async function handleSubmit() {
    setIsSubmitting(true)
    setErrorMessage(null)
    setSuccessMessage(null)

    try {
      const response = await fetch(
        editingId
          ? `/api/admin/payroll/${recordId}/adjustments/${editingId}`
          : `/api/admin/payroll/${recordId}/adjustments`,
        {
          method: editingId ? "PATCH" : "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            type: formState.type,
            source: formState.source,
            reason: formState.reason,
            amount: formState.amount,
          }),
        }
      )

      const data = await response.json().catch(() => null)

      if (!response.ok) {
        throw new Error(data?.error || "Failed to save payroll adjustment")
      }

      setSuccessMessage(
        editingId
          ? "Adjustment updated successfully."
          : "Adjustment added successfully."
      )
      resetForm()
      router.refresh()
    } catch (error) {
      setErrorMessage(
        error instanceof Error ? error.message : "Failed to save payroll adjustment"
      )
    } finally {
      setIsSubmitting(false)
    }
  }

  async function handleDelete(adjustmentId: string) {
    setIsSubmitting(true)
    setErrorMessage(null)
    setSuccessMessage(null)

    try {
      const response = await fetch(
        `/api/admin/payroll/${recordId}/adjustments/${adjustmentId}`,
        {
          method: "DELETE",
        }
      )

      const data = await response.json().catch(() => null)

      if (!response.ok) {
        throw new Error(data?.error || "Failed to delete payroll adjustment")
      }

      setSuccessMessage("Adjustment removed successfully.")
      if (editingId === adjustmentId) {
        resetForm()
      }
      router.refresh()
    } catch (error) {
      setErrorMessage(
        error instanceof Error ? error.message : "Failed to delete payroll adjustment"
      )
    } finally {
      setIsSubmitting(false)
    }
  }

  async function handleRecalculate() {
    setIsRecalculating(true)
    setErrorMessage(null)
    setSuccessMessage(null)

    try {
      const response = await fetch(`/api/admin/payroll/${recordId}/recalculate`, {
        method: "POST",
      })

      const data = await response.json().catch(() => null)

      if (!response.ok) {
        throw new Error(data?.error || "Failed to recalculate payroll adjustments")
      }

      setSuccessMessage("Automatic late and absence deductions recalculated.")
      router.refresh()
    } catch (error) {
      setErrorMessage(
        error instanceof Error
          ? error.message
          : "Failed to recalculate payroll adjustments"
      )
    } finally {
      setIsRecalculating(false)
    }
  }

  return (
    <Card>
      <CardHeader className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <CardTitle>Payroll Adjustments</CardTitle>
          <CardDescription>
            Bonuses, deductions, and advance adjustments that shape the final net salary.
          </CardDescription>
        </div>
        {canManage ? (
          <Button
            type="button"
            variant="outline"
            onClick={handleRecalculate}
            disabled={isRecalculating}
          >
            {isRecalculating ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <RefreshCcw className="mr-2 h-4 w-4" />
            )}
            Recalculate Auto Deductions
          </Button>
        ) : null}
      </CardHeader>
      <CardContent className="space-y-4">
        {canManage ? (
          <div className="space-y-4 rounded-lg border p-4">
            <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
              <div className="space-y-2">
                <label className="text-sm font-medium">Adjustment Type</label>
                <Select
                  value={formState.type}
                  onValueChange={(value) =>
                    setFormState((current) => ({
                      ...current,
                      type: value as PayrollAdjustmentType,
                    }))
                  }
                  disabled={isSubmitting}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select type" />
                  </SelectTrigger>
                  <SelectContent>
                    {Object.values(PayrollAdjustmentType).map((type) => (
                      <SelectItem key={type} value={type}>
                        {payrollAdjustmentTypeLabels[type]}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <label className="text-sm font-medium">Source</label>
                <Select
                  value={formState.source}
                  onValueChange={(value) =>
                    setFormState((current) => ({
                      ...current,
                      source: value as PayrollAdjustmentSource,
                    }))
                  }
                  disabled={isSubmitting}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select source" />
                  </SelectTrigger>
                  <SelectContent>
                    {Object.values(PayrollAdjustmentSource).map((source) => (
                      <SelectItem key={source} value={source}>
                        {payrollAdjustmentSourceLabels[source]}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2 xl:col-span-2">
                <label className="text-sm font-medium">Amount</label>
                <Input
                  type="number"
                  min="0.01"
                  step="0.01"
                  value={formState.amount}
                  onChange={(event) =>
                    setFormState((current) => ({
                      ...current,
                      amount: event.target.value,
                    }))
                  }
                  disabled={isSubmitting}
                />
              </div>
            </div>

            <div className="space-y-2">
              <label className="text-sm font-medium">Reason</label>
              <Textarea
                placeholder="Explain why this payroll adjustment applies..."
                value={formState.reason}
                onChange={(event) =>
                  setFormState((current) => ({
                    ...current,
                    reason: event.target.value,
                  }))
                }
                disabled={isSubmitting}
              />
            </div>

            <div className="flex flex-wrap justify-end gap-2">
              {editingId ? (
                <Button type="button" variant="ghost" onClick={resetForm} disabled={isSubmitting}>
                  Cancel Edit
                </Button>
              ) : null}
              <Button
                type="button"
                onClick={handleSubmit}
                disabled={
                  isSubmitting ||
                  !formState.reason.trim() ||
                  !formState.amount ||
                  Number(formState.amount) <= 0
                }
              >
                {isSubmitting ? (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                ) : editingId ? (
                  <Pencil className="mr-2 h-4 w-4" />
                ) : (
                  <PlusCircle className="mr-2 h-4 w-4" />
                )}
                {editingId ? "Update Adjustment" : "Add Adjustment"}
              </Button>
            </div>
          </div>
        ) : null}

        {errorMessage ? (
          <div className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">
            {errorMessage}
          </div>
        ) : null}

        {successMessage ? (
          <div className="rounded-md bg-green-100 p-3 text-sm text-green-800 dark:bg-green-950/40 dark:text-green-300">
            {successMessage}
          </div>
        ) : null}

        {adjustments.length === 0 ? (
          <div className="rounded-lg border border-dashed p-6 text-sm text-muted-foreground">
            No bonuses, deductions, or advance adjustments have been recorded for this payroll period yet.
          </div>
        ) : (
          <div className="rounded-lg border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Type</TableHead>
                  <TableHead>Source</TableHead>
                  <TableHead>Reason</TableHead>
                  <TableHead>Amount</TableHead>
                  <TableHead>Created</TableHead>
                  {canManage ? (
                    <TableHead className="text-right">Action</TableHead>
                  ) : null}
                </TableRow>
              </TableHeader>
              <TableBody>
                {adjustments.map((adjustment) => (
                  <TableRow key={adjustment.id}>
                    <TableCell>{payrollAdjustmentTypeLabels[adjustment.type]}</TableCell>
                    <TableCell>
                      <div>
                        <p>{payrollAdjustmentSourceLabels[adjustment.source as PayrollAdjustmentSource] || adjustment.source}</p>
                        <p className="text-xs text-muted-foreground">
                          {adjustment.isAutoGenerated ? "Automatic" : "Manual"}
                        </p>
                      </div>
                    </TableCell>
                    <TableCell>
                      <div>
                        <p className="font-medium">{adjustment.reason}</p>
                        {adjustment.createdBy ? (
                          <p className="text-xs text-muted-foreground">
                            Added by {adjustment.createdBy.firstName} {adjustment.createdBy.lastName}
                          </p>
                        ) : null}
                      </div>
                    </TableCell>
                    <TableCell
                      className={
                        adjustment.type === PayrollAdjustmentType.bonus
                          ? "text-green-600"
                          : "text-red-600"
                      }
                    >
                      {adjustment.type === PayrollAdjustmentType.bonus ? "+" : "-"}
                      <CurrencyAmount amount={adjustment.amount} currency={currency} />
                    </TableCell>
                    <TableCell>
                      {new Date(adjustment.createdAt).toLocaleDateString()}
                    </TableCell>
                    {canManage ? (
                      <TableCell className="text-right">
                        {!adjustment.isAutoGenerated ? (
                          <div className="flex justify-end gap-2">
                            <Button
                              type="button"
                              size="sm"
                              variant="outline"
                              onClick={() => startEdit(adjustment)}
                              disabled={isSubmitting}
                            >
                              <Pencil className="mr-2 h-3.5 w-3.5" />
                              Edit
                            </Button>
                            <Button
                              type="button"
                              size="sm"
                              variant="outline"
                              onClick={() => handleDelete(adjustment.id)}
                              disabled={isSubmitting}
                            >
                              <Trash2 className="mr-2 h-3.5 w-3.5" />
                              Remove
                            </Button>
                          </div>
                        ) : (
                          <span className="text-xs text-muted-foreground">
                            Auto rule
                          </span>
                        )}
                      </TableCell>
                    ) : null}
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        )}

        {canManage && manualAdjustments.length === 0 ? (
          <p className="text-xs text-muted-foreground">
            Manual adjustments are optional. Automatic late and absence deductions can be recalculated at any time before payroll is finalized.
          </p>
        ) : null}
      </CardContent>
    </Card>
  )
}
